platform :ios, ‘8.0’

target 'ios-quickeditor' do
  pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'
  pod 'Google/SignIn', '~> 3.0.3'

  target 'ios-quickeditorTests' do
    inherit! :search_paths
  end
end
